"""Generate an n8n automation blueprint (markdown + JSON files).

Blueprint only — nothing connects to a live n8n instance, and every service in
the flow has a free tier. The JSON includes both a readable node list (per the
product spec) and an n8n-import-style skeleton users can adapt.
"""

import json
from pathlib import Path

_NODES = [
    {
        "type": "webhook",
        "name": "Receive URL or report request",
        "n8n_type": "n8n-nodes-base.webhook",
        "purpose": "Entry point: a POST with {url, topic, audience} kicks off an audit.",
        "config_hint": "Method: POST · Path: /aiso-audit · Respond: when last node finishes.",
    },
    {
        "type": "http_request",
        "name": "Call AISO Copilot Analyze API",
        "n8n_type": "n8n-nodes-base.httpRequest",
        "purpose": "Runs the audit via the local FastAPI backend and returns the full JSON result.",
        "config_hint": "POST http://localhost:8000/analyze · Body: JSON from the webhook payload.",
    },
    {
        "type": "google_sheets",
        "name": "Append audit summary",
        "n8n_type": "n8n-nodes-base.googleSheets",
        "purpose": "Logs date, URL, overall readiness and subscores into a tracking sheet.",
        "config_hint": "Operation: Append · Map scores.* fields to columns.",
    },
    {
        "type": "google_docs",
        "name": "Create client report",
        "n8n_type": "n8n-nodes-base.googleDocs",
        "purpose": "Creates a Google Doc from the markdown audit report for client delivery.",
        "config_hint": "Operation: Create · Content: {{$json.report_markdown}}.",
    },
    {
        "type": "notification",
        "name": "Notify team",
        "n8n_type": "n8n-nodes-base.slack",
        "purpose": "Posts the readiness score and report link to Slack (or email instead).",
        "config_hint": "Channel: #ai-search-audits · Message includes overall score + doc link.",
    },
    {
        "type": "task_tracker",
        "name": "Create follow-up task",
        "n8n_type": "n8n-nodes-base.notion",
        "purpose": "Files the top priority actions as a task for human review and follow-up.",
        "config_hint": "Database: Client tasks · Title: 'AISO follow-up: {{$json.page.title}}'.",
    },
]

_NOTES = [
    "Blueprint only — this file is documentation, not a live connection. Import and adapt inside your own n8n instance.",
    "Designed for free tiers: self-hosted n8n (or free cloud trial), Google Sheets/Docs, Slack free plan, Notion free plan.",
    "Keep a human review step before any client-facing report is sent — the audit is decision support, not an autopilot.",
    "Do not chain this into bulk content generation or search-engine scraping workflows.",
]


def generate_n8n_blueprint(api_url: str = "http://localhost:8000/analyze",
                           project: str = "AISO Copilot") -> dict:
    nodes = []
    for node in _NODES:
        entry = {k: v for k, v in node.items() if k != "n8n_type"}
        if node["type"] == "http_request":
            entry["config_hint"] = entry["config_hint"].replace(
                "http://localhost:8000/analyze", api_url
            )
        nodes.append(entry)

    names = [n["name"] for n in _NODES]
    connections = [[names[i], names[i + 1]] for i in range(len(names) - 1)]

    skeleton = {
        "name": "AI Search Audit Report Automation",
        "nodes": [
            {
                "id": str(i + 1),
                "name": node["name"],
                "type": node["n8n_type"],
                "typeVersion": 1,
                "position": [240 + i * 220, 300],
                "parameters": {},
            }
            for i, node in enumerate(_NODES)
        ],
        "connections": {
            names[i]: {"main": [[{"node": names[i + 1], "type": "main", "index": 0}]]}
            for i in range(len(names) - 1)
        },
        "settings": {"executionOrder": "v1"},
    }

    return {
        "workflow_name": "AI Search Audit Report Automation",
        "project": project,
        "description": (
            "Receives an audit request, runs the AISO Copilot analyzer, logs the "
            "scores, creates a client report document, notifies the team, and files "
            "a follow-up task — with a human review before anything reaches a client."
        ),
        "nodes": nodes,
        "connections": connections,
        "n8n_import_skeleton": skeleton,
        "notes": list(_NOTES),
    }


def blueprint_markdown(blueprint: dict) -> str:
    lines = [
        f"# n8n Workflow Blueprint — {blueprint['workflow_name']}",
        "",
        f"> Generated by {blueprint['project']}. {blueprint['notes'][0]}",
        "",
        "## What it does",
        "",
        blueprint["description"],
        "",
        "## Flow",
        "",
        "```text",
        "  →  ".join(node["name"] for node in blueprint["nodes"]),
        "```",
        "",
        "## Nodes",
        "",
        "| # | Node | Type | Purpose | Setup hint |",
        "|---|------|------|---------|------------|",
    ]
    for i, node in enumerate(blueprint["nodes"], start=1):
        lines.append(
            f"| {i} | {node['name']} | `{node['type']}` | {node['purpose']} | {node['config_hint']} |"
        )
    lines += [
        "",
        "## Import skeleton",
        "",
        "An n8n-style JSON skeleton is included in `n8n_workflow_blueprint.json` under "
        "`n8n_import_skeleton` — import it into n8n and fill in credentials/parameters.",
        "",
        "## Notes",
        "",
    ]
    lines += [f"- {note}" for note in blueprint["notes"]]
    lines.append("")
    return "\n".join(lines)


def write_blueprint_files(blueprint: dict, workflows_dir) -> list:
    workflows_dir = Path(workflows_dir)
    workflows_dir.mkdir(parents=True, exist_ok=True)
    md_path = workflows_dir / "n8n_workflow_blueprint.md"
    json_path = workflows_dir / "n8n_workflow_blueprint.json"
    md_path.write_text(blueprint_markdown(blueprint), encoding="utf-8")
    json_path.write_text(
        json.dumps(blueprint, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return [str(md_path), str(json_path)]
